name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        default: "master"
      commitHash:
        description: "Commit Hash"
        default: "HEAD"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.3"

      - name: User Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Release
        run: npx semantic-release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
